micronaut:
  application:
    name: pooperUserApi
  caches:
    users:
      charset: 'UTF-8'
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:foobarbaz}
              jws-algorithm: HS256
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowCredentials: true
          allowedOrigins:
            - ${FRONTEND_BASE_URL:https://pooper.local}
    port: ${USER_API_PORT:7070}
netty:
  default:
    allocator:
      max-order: 3
datasources:
  pooper:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/pooper`}
    username: ${JDBC_USER:pooper}
    password: ${JDBC_PASSWORD:pooper}
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
jpa:
  default:
    entity-scan:
      packages: 'pooper.user.api.domain'